name = "session-proxy"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "SESSIONS", class_name = "SessionObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SessionObject"]
